# Generated by Django 5.0.4 on 2024-05-10 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("name", "league")},
        ),
    ]
