# Generated by Django 5.0.4 on 2024-05-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="team",
            name="name_short",
            field=models.CharField(max_length=4),
        ),
    ]
