# Generated by Django 5.0.4 on 2024-05-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0002_match"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="away_score",
            field=models.IntegerField(default=0, verbose_name="Score Équipe Extérieur"),
        ),
        migrations.AddField(
            model_name="match",
            name="home_score",
            field=models.IntegerField(default=0, verbose_name="Score Équipe Domicile"),
        ),
        migrations.AddField(
            model_name="match",
            name="played",
            field=models.BooleanField(default=False, verbose_name="Match Joué"),
        ),
    ]
