# Generated by Django 5.0.4 on 2024-05-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_teamleague'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='TeamLeague',
        ),
    ]
