# Generated by Django 5.0.4 on 2024-05-12 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0003_teamleague"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TeamLeague",
        ),
    ]
