# Generated by Django 5.0.4 on 2024-05-03 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0003_match_away_score_match_home_score_match_played"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField(default=0)),
                ("goals_for", models.IntegerField(default=0)),
                ("goals_against", models.IntegerField(default=0)),
                ("goal_difference", models.IntegerField(default=0)),
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="matches.team",
                    ),
                ),
            ],
        ),
    ]
