# Generated by Django 5.0.4 on 2024-05-03 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0004_teamstats"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teamstats",
            options={"verbose_name_plural": "Team Stats"},
        ),
        migrations.AlterField(
            model_name="match",
            name="away_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="match",
            name="away_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="away_matches",
                to="matches.team",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="match",
            name="home_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="match",
            name="home_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_matches",
                to="matches.team",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="played",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
