# Generated by Django 5.0.4 on 2024-05-03 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0005_alter_teamstats_options_alter_match_away_score_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teamstats",
            options={},
        ),
        migrations.AlterField(
            model_name="match",
            name="away_score",
            field=models.IntegerField(default=0, verbose_name="Score Équipe Extérieur"),
        ),
        migrations.AlterField(
            model_name="match",
            name="away_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="away_games",
                to="matches.team",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="date",
            field=models.DateField(verbose_name="Date du match"),
        ),
        migrations.AlterField(
            model_name="match",
            name="home_score",
            field=models.IntegerField(default=0, verbose_name="Score Équipe Domicile"),
        ),
        migrations.AlterField(
            model_name="match",
            name="home_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_games",
                to="matches.team",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="played",
            field=models.BooleanField(default=False, verbose_name="Match Joué"),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nom de l'équipe"),
        ),
    ]
