# Generated by Django 5.0.4 on 2024-05-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0006_alter_teamstats_options_alter_match_away_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="draws",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="games_played",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="goal_difference",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="goals_against",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="goals_for",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="losses",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="wins",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="TeamStats",
        ),
    ]
