# Generated by Django 5.0.4 on 2024-05-04 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0007_team_draws_team_games_played_team_goal_difference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="away_score",
            field=models.IntegerField(
                default="-",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Score Équipe Extérieur",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="home_score",
            field=models.IntegerField(
                default="-",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Score Équipe Domicile",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="goals_against",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="goals_for",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
