# Generated by Django 5.0.4 on 2024-04-30 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league", "0003_alter_team_goals_against_alter_team_goals_for"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="goals_team1",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="goals_team2",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
